insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'size_5'), 2, '10 to 19 employees', 1);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'size_5'), 4, '20 to 49 employees', 2);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'size_5'), 8, '50 to 249 employees', 3);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'size_5'), 16, '250 to 499 employees', 4);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'size_5'), 32, '500 or more employees', 5);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'sec3'), 2, 'Production sector', 1);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'sec3'), 4, 'Private Services', 2);
insert into answer_meanings(question_id, answer_bit, answer_text, position) values ((select id from questions where question_field = 'sec3'), 8, 'Public Services', 3);
update questions set question = 'Company Size' where question_field = 'size_5';
update questions set question = 'Sector Type' where question_field = 'sec3';
