try:
    from Products.OSHATranslations import OSHAMessageFactory as _
except ImportError:
    def _(x):
        return x
SHORT_NAME_TO_ID = dict((
        ('AL', '001'),
        ('AD', '002'),
        ('AT', '003'),
        ('BY', '004'),
        ('BE', '005'),
        ('BA', '006'),
        ('BG', '007'),
        ('HR', '008'),
        ('CZ', '009'),
        ('DK', '010'),
        ('EE', '011'),
        ('FI', '012'),
        ('FR', '013'),
        ('DE', '014'),
        ('GR', '015'),
        ('HU', '016'),
        ('IS', '017'),
        ('IE', '018'),
        ('IT', '019'),
        ('LV', '020'),
        ('LI', '021'),
        ('LT', '022'),
        ('LU', '023'),
        ('MK', '024'),
        ('MT', '025'),
        ('MD', '026'),
        ('MC', '027'),
        ('MO', '028'),
        ('NL', '029'),
        ('NO', '030'),
        ('PL', '031'),
        ('PT', '032'),
        ('RO', '033'),
        ('SM', '034'),
        ('CS', '035'),
        ('SK', '036'),
        ('SI', '037'),
        ('ES', '038'),
        ('SE', '039'),
        ('CH', '040'),
        ('UA', '041'),
        ('UK', '042'),
        ('VA', '043'),
        ('CY', '044'),
        ('TR', '045'),
        ('RU', '046'),
        ('SC', '047'),
        ('EN', '048'),
        ('NI', '049'),
        ('WA', '048'),
)) 

ID_TO_SHORT_NAME = dict([(x[1], x[0]) for x in SHORT_NAME_TO_ID.items()])

SHORT_NAME_TO_LONG = dict((
        ('AL', 'Albania'),
        ('AD', 'Andorra'),
        ('AT', 'Austria'),
        ('BY', 'Belarus'),
        ('BE', 'Belgium'),
        ('BA', 'Bosnia-Herzegovina'),
        ('BG', 'Bulgaria'),
        ('HR', 'Croatia'),
        ('CZ', 'Czech Republic'),
        ('DK', 'Denmark'),
        ('EE', 'Estonia'),
        ('FI', 'Finland'),
        ('FR', 'France'),
        ('DE', 'Germany'),
        ('GR', 'Greece'),
        ('HU', 'Hungary'),
        ('IS', 'Iceland'),
        ('IE', 'Ireland'),
        ('IT', 'Italy'),
        ('LV', 'Latvia'),
        ('LI', 'Liechtenstein'),
        ('LT', 'Lithuania'),
        ('LU', 'Luxembourg'),
        ('MK', 'Macedonia'),
        ('MT', 'Malta'),
        ('MD', 'Moldova'),
        ('MC', 'Monaco'),
        ('MO', 'Montenegro'),
        ('NL', 'Netherlands'),
        ('NO', 'Norway'),
        ('PL', 'Poland'),
        ('PT', 'Portugal'),
        ('RO', 'Romania'),
        ('SM', 'San Marino'),
        ('CS', 'Serbia'),
        ('SK', 'Slovakia'),
        ('SI', 'Slovenia'),
        ('ES', 'Spain'),
        ('SE', 'Sweden'),
        ('CH', 'Switzerland'),
        ('UA', 'Ukraine'),
        ('UK', 'United Kingdom'),
        ('VA', 'Vatican City'),
        ('CY', 'Cyprus'),
        ('TR', 'Turkey'),
        ('RU', 'Russia'),
        ('SC', 'Scotland'),
        ('EN', 'England'),
        ('NI', 'North Ireland'),
        ('WA', 'Wales'),
))

LONG_TO_TRANSLATED = dict((
        ('Albania', _('AL Albania')),
        ('Andorra', _('AD Andorra')),
        ('Austria', _('AT Austria')),
        ('Belarus', _('BY Belarus')),
        ('Belgium', _('BE Belgium')),
        ('Bosnia-Herzegovina', _('BA Bosnia-Herzegovina')),
        ('Bulgaria', _('BG Bulgaria')),
        ('Croatia', _('HR Croatia')),
        ('Czech Republic', _('CZ Czech Republic')),
        ('Denmark', _('DK Denmark')),
        ('Estonia', _('EE Estonia')),
        ('Finland', _('FI Finland')),
        ('France', _('FR France')),
        ('Germany', _('DE Germany')),
        ('Greece', _('GR Greece')),
        ('Hungary', _('HU Hungary')),
        ('Iceland', _('IS Iceland')),
        ('Ireland', _('IE Ireland')),
        ('Italy', _('IT Italy')),
        ('Latvia', _('LV Latvia')),
        ('Liechtenstein', _('LI Liechtenstein')),
        ('Lithuania', _('LT Lithuania')),
        ('Luxembourg', _('LU Luxembourg')),
        ('Macedonia', _('MK Macedonia')),
        ('Malta', _('MT Malta')),
        ('Moldova', _('MD Moldova')),
        ('Monaco', _('MC Monaco')),
        ('Montenegro', _('MO Montenegro')),
        ('Netherlands', _('NL Netherlands')),
        ('Norway', _('NO Norway')),
        ('Poland', _('PL Poland')),
        ('Portugal', _('PT Portugal')),
        ('Romania', _('RO Romania')),
        ('San Marino', _('SM San Marino')),
        ('Serbia', _('CS Serbia')),
        ('Slovakia', _('SK Slovakia')),
        ('Slovenia', _('SI Slovenia')),
        ('Spain', _('ES Spain')),
        ('Sweden', _('SE Sweden')),
        ('Switzerland', _('CH Switzerland')),
        ('Ukraine', _('UA Ukraine')),
        ('United Kingdom', _('UK United Kingdom')),
        ('Vatican City', _('VA Vatican City')),
        ('Cyprus', _('CY Cyprus')),
        ('Turkey', _('TR Turkey')),
        ('Russia', _('RU Russia')),
        ('Scotland', _('SC Scotland')),
        ('England', _('EN England')),
        ('North Ireland', _('NI North Ireland')),
        ('Wales', _('WA Wales')),
))


ID_TO_LONG_NAME = dict([(x[0], SHORT_NAME_TO_LONG[x[1]]) for x in ID_TO_SHORT_NAME.items()])
