try:
    from osha.theme import OSHAMessageFactory as _
except ImportError:
    def _(x):
        return x
SHORT_NAME_TO_ID = dict((
        ('AL', '001'),
        ('AD', '002'),
        ('AT', '003'),
        ('BY', '004'),
        ('BE', '005'),
        ('BA', '006'),
        ('BG', '007'),
        ('HR', '008'),
        ('CZ', '009'),
        ('DK', '010'),
        ('EE', '011'),
        ('FI', '012'),
        ('FR', '013'),
        ('DE', '014'),
        ('EL', '015'),
        ('HU', '016'),
        ('IS', '017'),
        ('IE', '018'),
        ('IT', '019'),
        ('LV', '020'),
        ('LI', '021'),
        ('LT', '022'),
        ('LU', '023'),
        ('MK', '024'),
        ('MT', '025'),
        ('MD', '026'),
        ('MC', '027'),
        ('MO', '028'),
        ('NL', '029'),
        ('NO', '030'),
        ('PL', '031'),
        ('PT', '032'),
        ('RO', '033'),
        ('SM', '034'),
        ('CS', '035'),
        ('SK', '036'),
        ('SI', '037'),
        ('ES', '038'),
        ('SE', '039'),
        ('CH', '040'),
        ('UA', '041'),
        ('UK', '042'),
        ('VA', '043'),
        ('CY', '044'),
        ('TR', '045'),
        ('RU', '046'),
        ('SC', '047'),
        ('EN', '048'),
        ('NI', '049'),
        ('WA', '048'),
)) 

ID_TO_SHORT_NAME = dict([(x[1], x[0]) for x in SHORT_NAME_TO_ID.items()])

SHORT_NAME_TO_LONG = dict((
        ('AL', 'Albania'),
        ('AD', 'Andorra'),
        ('AT', 'Austria'),
        ('BY', 'Belarus'),
        ('BE', 'Belgium'),
        ('BA', 'Bosnia-Herzegovina'),
        ('BG', 'Bulgaria'),
        ('HR', 'Croatia'),
        ('CZ', 'Czech Republic'),
        ('DK', 'Denmark'),
        ('EE', 'Estonia'),
        ('FI', 'Finland'),
        ('FR', 'France'),
        ('DE', 'Germany'),
        ('EL', 'Greece'),
        ('HU', 'Hungary'),
        ('IS', 'Iceland'),
        ('IE', 'Ireland'),
        ('IT', 'Italy'),
        ('LV', 'Latvia'),
        ('LI', 'Liechtenstein'),
        ('LT', 'Lithuania'),
        ('LU', 'Luxembourg'),
        ('MK', 'Macedonia'),
        ('MT', 'Malta'),
        ('MD', 'Moldova'),
        ('MC', 'Monaco'),
        ('MO', 'Montenegro'),
        ('NL', 'Netherlands'),
        ('NO', 'Norway'),
        ('PL', 'Poland'),
        ('PT', 'Portugal'),
        ('RO', 'Romania'),
        ('SM', 'San Marino'),
        ('CS', 'Serbia'),
        ('SK', 'Slovakia'),
        ('SI', 'Slovenia'),
        ('ES', 'Spain'),
        ('SE', 'Sweden'),
        ('CH', 'Switzerland'),
        ('UA', 'Ukraine'),
        ('UK', 'United Kingdom'),
        ('VA', 'Vatican City'),
        ('CY', 'Cyprus'),
        ('TR', 'Turkey'),
        ('RU', 'Russia'),
        ('SC', 'Scotland'),
        ('EN', 'England'),
        ('NI', 'North Ireland'),
        ('WA', 'Wales'),
))

LONG_TO_TRANSLATED = dict((
        ('Albania', 'AL Albania'),
        ('Andorra', 'AD Andorra'),
        ('Austria', 'AT Austria'),
        ('Belarus', 'BY Belarus'),
        ('Belgium', 'BE Belgium'),
        ('Bosnia-Herzegovina', 'BA Bosnia-Herzegovina'),
        ('Bulgaria', 'BG Bulgaria'),
        ('Croatia', 'HR Croatia'),
        ('Czech Republic', 'CZ Czech Republic'),
        ('Denmark', 'DK Denmark'),
        ('Estonia', 'EE Estonia'),
        ('Finland', 'FI Finland'),
        ('France', 'FR France'),
        ('Germany', 'DE Germany'),
        ('Greece', 'EL Greece'),
        ('Hungary', 'HU Hungary'),
        ('Iceland', 'IS Iceland'),
        ('Ireland', 'IE Ireland'),
        ('Italy', 'IT Italy'),
        ('Latvia', 'LV Latvia'),
        ('Liechtenstein', 'LI Liechtenstein'),
        ('Lithuania', 'LT Lithuania'),
        ('Luxembourg', 'LU Luxembourg'),
        ('Macedonia', 'MK Macedonia'),
        ('Malta', 'MT Malta'),
        ('Moldova', 'MD Moldova'),
        ('Monaco', 'MC Monaco'),
        ('Montenegro', 'MO Montenegro'),
        ('Netherlands', 'NL Netherlands'),
        ('Norway', 'NO Norway'),
        ('Poland', 'PL Poland'),
        ('Portugal', 'PT Portugal'),
        ('Romania', 'RO Romania'),
        ('San Marino', 'SM San Marino'),
        ('Serbia', 'CS Serbia'),
        ('Slovakia', 'SK Slovakia'),
        ('Slovenia', 'SI Slovenia'),
        ('Spain', 'ES Spain'),
        ('Sweden', 'SE Sweden'),
        ('Switzerland', 'CH Switzerland'),
        ('Ukraine', 'UA Ukraine'),
        ('United Kingdom', 'UK United Kingdom'),
        ('Vatican City', 'VA Vatican City'),
        ('Cyprus', 'CY Cyprus'),
        ('Turkey', 'TR Turkey'),
        ('Russia', 'RU Russia'),
        ('Scotland', 'SC Scotland'),
        ('England', 'EN England'),
        ('North Ireland', 'NI North Ireland'),
        ('Wales', 'WA Wales'),
))


ID_TO_LONG_NAME = dict([(x[0], SHORT_NAME_TO_LONG[x[1]]) for x in ID_TO_SHORT_NAME.items()])
